import { z } from 'zod';

export const singleProductSchema = z.object({
  supplier: z.string().min(1, 'Supplier is required'),
  bill_number: z.string().min(1, 'Bill number is required'),
  received_date: z.string().min(1, 'Date is required'),
  manufacturer: z.string().min(1, 'Manufacturer is required'),
  barcode: z.string().optional(),
  pack: z.string().min(1, 'Pack is required'),
  batch_code: z.string().min(1, 'Batch code is required'),
  expiry_date: z.string().min(1, 'Expiry date is required'),
  quantity: z.number().min(0, 'Quantity must be positive'),
  f_qty: z.number().min(0),
  half_qty: z.number().min(0),
  purchase_rate: z.number().min(0),
  sale_rate: z.number().min(0),
  mrp: z.number().min(0),
  discount: z.number().min(0),
  cgst: z.number().min(0),
  sgst: z.number().min(0),
  igst: z.number().min(0),
  additional_vat: z.number().min(0),
  amount: z.number().min(0),
  local_cent: z.number().min(0),
  scm1: z.number().min(0),
  scm2: z.number().min(0),
  scm_percentage: z.number().min(0),
  tcs_percentage: z.number().min(0),
  tcs_amount: z.number().min(0),
  po_number: z.string().optional(),
  po_date: z.string().optional(),
  hsn_code: z.string().min(1, 'HSN code is required'),
});
